import { describe, it, expect, beforeEach, vi } from 'vitest';
import { EventBus } from '../../core/EventBus.js';
import { EV } from '../../event-constants.js';

const mockStore = { current: null };

vi.mock('../../dataManager/dataManager.js', () => ({
  DataManager: { getInstance: () => mockStore.current },
}));

let mockMgr;

function createContainer() {
  const div = document.createElement('div');
  document.body.appendChild(div);
  return div;
}

let eb, container, panel;

beforeEach(async () => {
  eb = new EventBus();
  container = createContainer();

  mockStore.current = {
    userId: 'god_1',
    userType: 'god',
    gameState: 'in_gaming',
    gamePhase: 'night_1',
    playerList: [],
    eventLogs: [],
    spyActive: false,
    localRoleNotes: {},
    sendEventRecord: vi.fn(),
    sendEventDelete: vi.fn(),
  };

  mockMgr = {
    currentViewPhase: 'night_1',
    setViewPhase: vi.fn(),
    getEventsByPhase: vi.fn(() => []),
    getEventById: vi.fn(),
    deleteEvent: vi.fn(),
    recordQuickEvent: vi.fn(),
    updateQuickEvent: vi.fn(),
    getPlayerDisplayList: vi.fn(() => [
      { playerId: 'p1', nickName: '小明', roleName: '占卜师', stateNow: 'alive', seatNum: 0 },
    ]),
  };

  const { EventLogPanel } = await import('../EventLogPanel.js');
  panel = new EventLogPanel(eb, container, mockMgr);
});

describe('EventLogPanel', () => {
  it('构造时创建完整 DOM', () => {
    expect(container.querySelector('.event-log-panel')).toBeTruthy();
    expect(container.querySelector('.el-phase-title')).toBeTruthy();
    expect(container.querySelector('.el-record-btn')).toBeTruthy();
  });

  it('show 显示面板', () => {
    panel.show();
    expect(container.querySelector('.event-log-panel').classList.contains('hidden')).toBe(false);
    expect(mockMgr.setViewPhase).toHaveBeenCalledWith('night_1');
  });

  it('show 发送 EVENT_LOG_SHOWN', () => {
    const spy = vi.fn();
    eb.on(EV.EVENT_LOG_SHOWN, spy);
    panel.show();
    expect(spy).toHaveBeenCalled();
  });

  it('hide 隐藏面板', () => {
    panel.show();
    panel.hide();
    expect(container.querySelector('.event-log-panel').classList.contains('hidden')).toBe(true);
  });

  it('事件列表渲染空状态', () => {
    mockMgr.getEventsByPhase = vi.fn(() => []);
    panel._renderEventList();
    expect(container.querySelector('.el-empty')).toBeTruthy();
  });

  it('事件列表渲染事件项', () => {
    mockMgr.getEventsByPhase = vi.fn(() => [
      { id: 'e1', phase: 'night_1', type: 'death', description: '死亡事件', playerIds: ['p1'], autoGenerated: true },
    ]);
    panel._renderEventList();
    expect(container.querySelectorAll('.el-event-item').length).toBe(1);
  });

  it('deleteEvent 调用 mgr', () => {
    panel._deleteEvent('e99');
    expect(mockMgr.deleteEvent).toHaveBeenCalledWith('e99');
  });

  it('响应 EVENT_REMOTE_SYNC', () => {
    panel.show();
    eb.emit(EV.EVENT_REMOTE_SYNC);
    // 不应报错
    expect(container.querySelector('.event-log-panel')).toBeTruthy();
  });
});
