import { EV, QUICK_EVENT_TEMPLATES, QUICK_EVENT_TYPE_MAP } from './event-constants.js';
import { DataManager } from './dataManager/dataManager.js';

export const PHASE_SEQUENCE = (() => {
  const seq = [];
  for (let n = 1; n < 20; n++) {
    seq.push(`night_${n}`, `day_${n + 1}`);
  }
  return seq;
})();

export const PHASE_LABELS = {
  'night_1': '第一夜', 'day_2': '第二日',
  'night_2': '第二夜', 'day_3': '第三日',
  'night_3': '第三夜', 'day_4': '第四日',
  'night_4': '第四夜', 'day_5': '第五日',
  'night_5': '第五夜', 'day_6': '第六日',
  'night_6': '第六夜', 'day_7': '第七日',
  'night_7': '第七夜', 'day_8': '第八日',
  'night_8': '第八夜', 'day_9': '第九日',
  'night_9': '第九夜', 'day_10': '第十日',
  'night_10': '第十夜', 'day_11': '第十一日',
  'night_11': '第十一夜', 'day_12': '第十二日',
  'night_12': '第十二夜', 'day_13': '第十三日',
  'night_13': '第十三夜', 'day_14': '第十四日',
  'night_14': '第十四夜', 'day_15': '第十五日',
  'night_15': '第十五夜', 'day_16': '第十六日',
  'night_16': '第十六夜', 'day_17': '第十七日',
  'night_17': '第十七夜', 'day_18': '第十八日',
  'night_18': '第十八夜', 'day_19': '第十九日',
  'night_19': '第十九夜', 'day_20': '第二十日',
};

const STATE_LABELS = {
  'dead_with_ticket': '死亡有票',
  'dead_without_ticket': '死亡无票',
  'alive': '存活',
};

export class EventLogManager {
  constructor(eventBus) {
    this.eventBus = eventBus;
    this.data = DataManager.getInstance();
    this.events = this.data.eventLogs && this.data.eventLogs.length > 0 ? [...this.data.eventLogs] : [];
    this._lastGameState = null;
    this._spyEvents = null;
    this.currentViewPhase = this.data.gamePhase || PHASE_SEQUENCE[0];
    this._bindAutoRecord();
  }

  _bindAutoRecord() {
    this._onStatusChange = ({ targetPlayerId, newState }) => {
      const player = this.data.playerList.find(p => p.playerId === targetPlayerId);
      const name = player ? `${player.nickName || '玩家'}（${player.avatarName || '???'}）` : '未知玩家';
      const stateLabel = STATE_LABELS[newState] || newState;
      const type = newState === 'alive' ? 'alive' : 'death';
      this._addEvent({
        phase: this.data.gamePhase,
        type,
        description: `${name} 被设置为${stateLabel}`,
        playerIds: [targetPlayerId],
        autoGenerated: true,
      });
    };
    this.eventBus.on(EV.PLAYER_STATUS_CHANGE, this._onStatusChange);

    this._onPhaseChanged = (phase) => {
      if (this.events.some(e => e.type === 'phase_change' && e.phase === phase)) return;
      this._addEvent({
        phase,
        type: 'phase_change',
        description: `游戏进入${PHASE_LABELS[phase] || phase}`,
        playerIds: [],
        autoGenerated: true,
      });
      if (!this._userNavigated) {
        this.currentViewPhase = phase;
      }
    };
    this.eventBus.on(EV.GAME_PHASE_CHANGED, this._onPhaseChanged);

    this._onStateChange = (newState) => {
      if (newState === 'in_gaming' && this._lastGameState === 'preparing') {
        this.events = [];
        this.currentViewPhase = this.data.gamePhase || PHASE_SEQUENCE[0];
        this._addEvent({
          phase: this.data.gamePhase,
          type: 'game_start',
          description: '游戏开始',
          playerIds: [],
          autoGenerated: true,
        });
      }
      if (newState === 'ended' && this._lastGameState !== 'ended') {
        this._addEvent({
          phase: this.data.gamePhase,
          type: 'game_end',
          description: '游戏结束，进入复盘',
          playerIds: [],
          autoGenerated: true,
        });
      }
      this._lastGameState = newState;
    };
    this.eventBus.on(EV.CHANGE_STATE, this._onStateChange);

    this._onRemoteRecord = (eventData) => {
      const idx = this.events.findIndex(e => e.id === eventData.id);
      if (idx >= 0) {
        this.events[idx] = eventData;
      } else {
        this.events.push(eventData);
      }
    };
    this.eventBus.on(EV.EVENT_REMOTE_RECORD, this._onRemoteRecord);

    this._onRemoteDelete = (eventId) => {
      this.events = this.events.filter(e => e.id !== eventId);
    };
    this.eventBus.on(EV.EVENT_REMOTE_DELETE, this._onRemoteDelete);

    this._onRemoteSync = (events) => {
      this.events = [...events];
    };
    this.eventBus.on(EV.EVENT_REMOTE_SYNC, this._onRemoteSync);
  }

  _addEvent(evt) {
    const eventData = {
      id: 'evt_' + Date.now() + '_' + Math.random().toString(36).slice(2, 6),
      gameTime: Date.now(),
      localOnly: this.data.userType !== 'god',
      ...evt,
    };
    this.events.push(eventData);
    if (this.data.userType === 'god') {
      this.data.sendEventRecord(eventData);
    }
  }

  getEventsByPhase(phase) {
    const source = (this.data.spyActive && this._spyEvents) ? this._spyEvents : this.events;
    return source.filter(e => e.phase === phase);
  }

  getPhasesWithEvents() {
    const source = (this.data.spyActive && this._spyEvents) ? this._spyEvents : this.events;
    const phases = new Set(source.map(e => e.phase));
    return [...phases].sort((a, b) => PHASE_SEQUENCE.indexOf(a) - PHASE_SEQUENCE.indexOf(b));
  }

  getPlayerDisplayList() {
    const isGod = this.data.userType === 'god';
    const myId = this.data.userId;
    const seated = this.data.playerList.filter(p => p.seatNum !== null);
    return seated.map(p => {
      let roleName = '';
      if (isGod || p.playerId === myId) {
        roleName = p.avatarName || '未选角';
      } else {
        const note = this.data.localRoleNotes[p.playerId];
        roleName = (note && note.avatarName) ? note.avatarName : '???';
      }
      return {
        playerId: p.playerId,
        nickName: p.nickName || '玩家',
        roleName,
        stateNow: p.stateNow || 'alive',
        seatNum: p.seatNum,
      };
    });
  }

  setViewPhase(phase) {
    this.currentViewPhase = phase;
  }

  navigatePhase(direction) {
    this._userNavigated = true;
    const idx = PHASE_SEQUENCE.indexOf(this.currentViewPhase);
    if (direction === 'prev' && idx > 0) {
      this.currentViewPhase = PHASE_SEQUENCE[idx - 1];
    } else if (direction === 'next' && idx < PHASE_SEQUENCE.length - 1) {
      this.currentViewPhase = PHASE_SEQUENCE[idx + 1];
    }
    return this.currentViewPhase;
  }

  _formatPlayerName(playerId) {
    const player = this.data.playerList.find(p => p.playerId === playerId);
    if (!player) return '未知玩家';
    const seatLabel = player.seatNum !== null ? `${player.seatNum + 1}号` : '';
    const name = player.nickName || '玩家';
    let role;
    if (this.data.userType === 'god' || playerId === this.data.userId) {
      role = player.avatarName || '未选角';
    } else {
      const note = this.data.localRoleNotes[playerId];
      role = (note && note.avatarName) ? note.avatarName : '???';
    }
    return `${seatLabel}${name}（${role}）`;
  }

  _buildDescParts(templateId, filledPlayerIds, numberValue, roleName) {
    const template = QUICK_EVENT_TEMPLATES.find(t => t.id === templateId);
    if (!template) return null;
    const text = template.text;
    const parts = [];
    const regex = /\{(\d|n|role)\}/g;
    let match;
    let lastIdx = 0;
    while ((match = regex.exec(text)) !== null) {
      if (match.index > lastIdx) {
        parts.push({ type: 'text', value: text.substring(lastIdx, match.index) });
      }
      if (match[1] === 'n') {
        parts.push({ type: 'number', value: String(numberValue || 0) });
      } else if (match[1] === 'role') {
        parts.push({ type: 'role', value: roleName || '' });
      } else {
        const idx = parseInt(match[1]);
        const pid = filledPlayerIds[idx];
        parts.push({ type: 'player', value: pid ? this._formatPlayerName(pid) : '???' });
      }
      lastIdx = match.index + match[0].length;
    }
    if (lastIdx < text.length) {
      parts.push({ type: 'text', value: text.substring(lastIdx) });
    }
    return parts;
  }

  recordQuickEvent(templateId, filledPlayerIds, numberValue, roleName) {
    const template = QUICK_EVENT_TEMPLATES.find(t => t.id === templateId);
    if (!template) return null;
    let desc = template.text;
    filledPlayerIds.forEach((pid, i) => {
      desc = desc.replace(`{${i}}`, this._formatPlayerName(pid));
    });
    if (template.hasNumber && numberValue !== undefined) {
      desc = desc.replace('{n}', numberValue);
    }
    if (roleName !== undefined) {
      desc = desc.replace('{role}', roleName);
    }
    const type = QUICK_EVENT_TYPE_MAP[templateId] || 'custom';
    const descParts = this._buildDescParts(templateId, filledPlayerIds, numberValue, roleName);
    this._addEvent({
      phase: this.currentViewPhase,
      type,
      description: desc,
      descParts,
      playerIds: filledPlayerIds.filter(Boolean),
      autoGenerated: false,
      templateId,
      quickNumberValue: numberValue,
      quickRoleName: roleName || '',
    });
    return desc;
  }

  updateQuickEvent(eventId, templateId, filledPlayerIds, numberValue, roleName) {
    const evt = this.events.find(e => e.id === eventId);
    if (!evt) return null;
    const template = QUICK_EVENT_TEMPLATES.find(t => t.id === templateId);
    if (!template) return null;
    let desc = template.text;
    filledPlayerIds.forEach((pid, i) => {
      desc = desc.replace(`{${i}}`, this._formatPlayerName(pid));
    });
    if (template.hasNumber && numberValue !== undefined) {
      desc = desc.replace('{n}', numberValue);
    }
    if (roleName !== undefined) {
      desc = desc.replace('{role}', roleName);
    }
    const type = QUICK_EVENT_TYPE_MAP[templateId] || 'custom';
    const descParts = this._buildDescParts(templateId, filledPlayerIds, numberValue, roleName);
    evt.type = type;
    evt.description = desc;
    evt.descParts = descParts;
    evt.playerIds = filledPlayerIds.filter(Boolean);
    evt.templateId = templateId;
    evt.quickNumberValue = numberValue;
    evt.quickRoleName = roleName || '';
    if (this.data.userType === 'god') {
      this.data.sendEventRecord(evt);
    }
    return desc;
  }

  deleteEvent(eventId) {
    const isGod = this.data.userType === 'god';
    this.events = this.events.filter(e => e.id !== eventId);
    if (isGod) {
      this.data.sendEventDelete(eventId);
    }
  }

  setSpyEvents(events) {
    this._spyEvents = events;
  }

  getEventById(eventId) {
    return this.events.find(e => e.id === eventId);
  }

  destroy() {
    this.eventBus.off(EV.PLAYER_STATUS_CHANGE, this._onStatusChange);
    this.eventBus.off(EV.GAME_PHASE_CHANGED, this._onPhaseChanged);
    this.eventBus.off(EV.CHANGE_STATE, this._onStateChange);
    this.eventBus.off(EV.EVENT_REMOTE_RECORD, this._onRemoteRecord);
    this.eventBus.off(EV.EVENT_REMOTE_DELETE, this._onRemoteDelete);
    this.eventBus.off(EV.EVENT_REMOTE_SYNC, this._onRemoteSync);
  }
}
